so in python you can't change variable in nested functions but lists you can

In [2]:
def outer(k):
    def inner():
        #if you put nonlocal then it binds to the most closest outer level scope
        # nonlocal k
        k+=1
        print(k)

    inner()
    print(k)


outer(1)


UnboundLocalError: local variable 'k' referenced before assignment

In [18]:
class Sol:
    def outer(self,k):
        
        self.k=k
        self.inner()
        print(k)


    def inner(self):
        #if you put nonlocal then it binds to the most closest outer level scope
        # nonlocal k
        self.k += 1
        print(self.k)

    # def __init__(self,k):
    #     self.k = k
Sol().outer(1)
    


2
1


In [ ]:
def outer(k):
    def inner():
        
            
            k.append(10)
            print(k)
        
    inner()
    print(k)
        
        
outer([1,2])


[1, 2, 10]
[1, 2, 10]


In [6]:
str="Sayan"
res=[]
for i in range(1,len(str)+1):
    res.append(str[-i])
output = "".join(res)
output

'nayaS'

In [2]:
str="Sayan"
res=str[::-1]
res

'nayaS'

In [14]:
import collections
walk = ['s', 'n', 's', 'n', 's', 'n']
map=collections.Counter(walk)
# map = {}
# for c in walk:
#     map[c] = 1+map.get(c, 0)

print(map)
sum(map.values())
print(map['w'])
map.get('n', 0) == map.get('s', 0) and map.get(
    'e', 0) == map.get('w', 0) and sum(map.values()) < 11


Counter({'s': 3, 'n': 3})
0


True

In [20]:
res=(255,0,255)
def rgb(r, g, b):
    # def round(a):
    #     a=max(0,min(255,a))
    #     return a

    def round(a): return max(0, min(255, a))
  

    return '{:02X}{:02X}{:02X}'.format(round(r),round(g),round(b))

rgb(257,2,-26)


'FF0200'

In [26]:
def pig_it(text):
#In this the expression has conditions : this is not a filter in list comprehension
    return ' '.join([(x[1:]+x[0]+'ay' if x.isalpha() else x)  for x in text.split()])
#this is a filter for list comprehension
    return ' '.join([(x[1:]+x[0]+'ay') for x in text.split() if x.isalpha()])




In [29]:
n=45
res=1
while n>0:
    res=res+ n**3
    n-=1
res
    
    

1071226

In [37]:
m = 1071226
from math import floor,sqrt
n_c=int(floor(sqrt(2*sqrt(m))))
print(n_c)

45


In [40]:
n=39
res=1
while n>0:
    res=res*(n%10)
    n=n//2
    print(res)

9
81
729
2916
5832
5832


In [44]:
import functools,operator

x=[1,2,3,4,5]

res=functools.reduce(operator.add,x)
print(res)

15


In [2]:
prerequisites = [[1, 0], [0, 1]]
map = {a: b for [a, b] in prerequisites}
print(map)


{1: 0, 0: 1}


In [12]:
# words="is2 Thi1s T4est 3a"
words='1d 2f 3e 4a'
def order(words):
    res = words.split()
    print(res)
    return ' '.join(sorted(res), key=lambda w: sorted(w))
order(words)


['1d', '2f', '3e', '4a']


'1d 2f 3e 4a'

In [16]:
res=[i*10 for i in range(len(words))]
res

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [21]:
numcourses=10
adj_list = {i: [] for i in range(numcourses)}
adj_list


{0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: []}

In [7]:
import numpy as np
def snail(arr):
    res=[]
    arr=np.array(arr)
    while(len(arr)>0):
        res+=arr[0].tolist()
        print(arr)
        print(res)
        arr=np.rot90(arr[1:])
    
        
    

In [8]:
array = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

snail(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3]
[[6 9]
 [5 8]
 [4 7]]
[1, 2, 3, 6, 9]
[[8 7]
 [5 4]]
[1, 2, 3, 6, 9, 8, 7]
[[4]
 [5]]
[1, 2, 3, 6, 9, 8, 7, 4]
[[5]]
[1, 2, 3, 6, 9, 8, 7, 4, 5]
[]
[1, 2, 3, 6, 9, 8, 7, 4, 5]


In [10]:
s='sayan'
s=list(s)
print(s)

['s', 'a', 'y', 'a', 'n']


In [14]:
prerequisites = [[1, 0], [2, 0], [3, 1], [3, 2]]
map = {i: [] for i in range(4)}
for course, pre in prerequisites:
    map[pre].append(course)
    
map


{0: [1, 2], 1: [3], 2: [3], 3: []}

In [21]:
edges = [[1, 2], [1, 3], [2, 3]]

print(map)


SyntaxError: invalid syntax (<ipython-input-21-a474d9c529cc>, line 2)

In [19]:
map = {i[0]: [] for i in edges}
for v1, v2 in edges:
    map[v1].append(v2)
    map[v2].append(v1)


KeyError: 3

In [4]:
class CustomInt(int):
    def __call__(self, v):
        return CustomInt(self + v)


def add(num):
    return CustomInt(num)

add(2)(2)


4

In [12]:
s='17'
i=0
if i+1 < len(s) and ((s[i] == '1' or s[i] == '2') and s[i+1] < '7'):
    print('done')

In [5]:
text1 = "abcde"
text2 = "ace"
dp=[[0 for i in range(len(text1))] for j in range(len(text2))]
dp

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [6]:
-2147483648//10

-214748365