![](2023-02-06-21-27-21.png)

In [8]:
import numpy as np
def minDistance( word1: str, word2: str) -> int:
    cache=[[float('inf')]*(len(word2)+1) for i in range(len(word1)+1)]

    for j in range(len(word2)+1):
        cache[0][j]=j
    
    
    for i in range(len(word1)+1):
        cache[i][0]=i
    
    for i in range(1,len(word1)+1):
        for j in range(1,len(word2)+1):
            if word1[i-1]==word2[j-1]:
                cache[i][j]=cache[i-1][j-1]
            else:
                cache[i][j]=1+ min(cache[i-1][j],cache[i][j-1],cache[i-1][j-1])
    print(np.matrix(cache).view())
    return cache[-1][-1]

In [9]:
word2='acd'
word1='abd'
minDistance(word1,word2)

[[0 1 2 3]
 [1 0 1 2]
 [2 1 1 2]
 [3 2 2 1]]


1