![](rotate_image.jpg)

In [2]:
def rotate(matrix):
    
    r, l = len(matrix)-1, 0

    while l < r:

        #this will rotate a single layer of the square matrix
        for i in range(l-l, r-l):
            #r-l as the last element in each row is already rotated in first rotation
            #also the rotation for each different group in layer is shifted by (0,r-l)

            #i will be used to move to me next element in the layer to be rotated

            top, bottom = l, r
            #save the top left value
            save_top_left = matrix[top][l+i]
            #copy bottom left to top left
            matrix[top][l+i] = matrix[bottom-i][l]
            #copy bottom right to bottom left
            matrix[bottom-i][l] = matrix[bottom][r-i]
            #copy top right to bottom right
            matrix[bottom][r-i] = matrix[top+i][r]
            #copy the top left to top right
            matrix[top+i][r] = save_top_left

        r -= 1
        l += 1


In [6]:
import numpy as np
matrix=[[2,29,20,26,16,28],
        [12,27,9,25,13,21],
        [32,33,32,2,28,14],
        [13,14,32,27,22,26],
        [33,1,20,7,21,7],
        [4,24,1,6,32,34]]
rotate(matrix)
print(np.matrix(matrix).view())


[[ 4 33 13 32 12  2]
 [24  1 14 33 27 29]
 [ 1 20 32 32  9 20]
 [ 6  7 27  2 25 26]
 [32 21 22 28 13 16]
 [34  7 26 14 21 28]]
