![](2022-12-30-03-44-13.png)

### algo 1: O(m.n) just make copy and update rows and cols in copy then copy back to original
### algo 2: O(m+n) take 2 arrays update rows and cols array then update to original
### algo 3: O(1) take 2 arrays which are the first row and col of the matrix itself and 1 extra cell to avoid overlap then do above.

In [10]:
import numpy as np
def setZeroes(matrix):
   
    setrow0 = 1

    for r in range(len(matrix)):
        for c in range(len(matrix[0])):
            if matrix[r][c] == 0:
                matrix[0][c] = 0
                if r > 0:
                    matrix[r][0] = 0
                else:
                    setrow0 = 0
    print(np.matrix(matrix).view(), setrow0)
    for r in range(1, len(matrix)):
        for c in range(1, len(matrix[0])):
            if matrix[r][0] == 0 or matrix[0][c] ==0:
                matrix[r][c] = 0
    print(np.matrix(matrix).view(), setrow0)
    if matrix[0][0] == 0:
        for r in range(len(matrix)):
            matrix[r][0] = 0
    print(np.matrix(matrix).view(), setrow0)
    if setrow0 == 0:
        for c in range(len(matrix[0])):
            matrix[0][c] = 0


In [11]:
import numpy as np
matrix=[[1,1,1],[1,0,1],[1,1,1]]
setZeroes(matrix)
print(np.matrix(matrix).view())

[[1 0 1]
 [0 0 1]
 [1 1 1]] 1
[[1 0 1]
 [0 0 0]
 [1 0 1]] 1
[[1 0 1]
 [0 0 0]
 [1 0 1]] 1
[[1 0 1]
 [0 0 0]
 [1 0 1]]
